/**
 * Utilities for preparing model messages and wrapping tools for Vercel AI SDK.
 *
 * - {@link prepareModelMessages} encapsulates the full pipeline:
 *   `convertToModelMessages` → `slice` → `pruneMessages` → `sanitizeModelMessages`
 *
 * - {@link wrapToolsForVercelAi} converts SDK tools (from `toolsToAiTools`) into
 *   Vercel AI SDK `tool()` instances ready for `streamText()`.
 *
 * @module
 */

import {
  convertToModelMessages,
  pruneMessages,
  tool,
  zodSchema,
  type UIMessage,
} from 'ai';
import { sanitizeModelMessages } from './sanitize-model-messages.js';

// ---------------------------------------------------------------------------
// prepareModelMessages
// ---------------------------------------------------------------------------

export interface PrepareModelMessagesOptions {
  /** Max model messages to keep after slicing (default: 12). */
  maxContextMessages?: number;
  /** Override pruneMessages config. */
  pruneConfig?: {
    /** How to handle reasoning blocks (default: 'none'). */
    reasoning?: 'none' | 'keep';
    /** Tool-call pruning strategy (default: 'before-last-3-messages'). */
    toolCalls?: string;
    /** Empty message handling (default: 'remove'). */
    emptyMessages?: 'remove' | 'keep';
  };
}

/**
 * Convert UI messages into sanitized model messages ready for `streamText()`.
 *
 * Pipeline:
 * 1. `convertToModelMessages` (with `ignoreIncompleteToolCalls: true`)
 * 2. Slice to `maxContextMessages`
 * 3. `pruneMessages` — remove old reasoning / tool-calls / empty messages
 * 4. `sanitizeModelMessages` — strip orphaned tool-calls for OpenAI compatibility
 *
 * @example
 * ```ts
 * import { prepareModelMessages } from './index.js';
 *
 * const messages = await prepareModelMessages(uiMessages, {
 *   maxContextMessages: 12,
 * });
 * // messages is safe to pass to streamText()
 * ```
 */
export async function prepareModelMessages(
  uiMessages: UIMessage[],
  options?: PrepareModelMessagesOptions,
): Promise<unknown[]> {
  const maxCtx = options?.maxContextMessages ?? 12;

  const raw = await convertToModelMessages(uiMessages, {
    ignoreIncompleteToolCalls: true,
  });

  const sliced = raw.slice(-maxCtx);

  const pruned = pruneMessages({
    messages: sliced,
    reasoning: (options?.pruneConfig?.reasoning ?? 'none') as 'none',
    toolCalls: (options?.pruneConfig?.toolCalls ??
      'before-last-3-messages') as 'before-last-3-messages',
    emptyMessages: (options?.pruneConfig?.emptyMessages ?? 'remove') as 'remove',
  });

  const sanitized = sanitizeModelMessages(pruned);

  // Strip uiAction from tool-result parts — the LLM doesn't need them
  // (uiActions are auto-generated by SDK templates and consumed by the client)
  return stripUiActionsFromToolResults(sanitized);
}

// ---------------------------------------------------------------------------
// stripUiActionsFromToolResults
// ---------------------------------------------------------------------------

/**
 * Remove `uiAction` fields from tool-result parts in model messages.
 *
 * UI actions are auto-generated by SDK templates (uiActionOnSuccess, uiPattern)
 * and consumed by the client for toasts, navigation, and refreshes. The LLM
 * doesn't generate or use them — keeping them wastes 100-500 tokens per call.
 *
 * This runs AFTER sanitization so it doesn't interfere with orphan detection.
 */
function stripUiActionsFromToolResults<T>(messages: T[]): T[] {
  return messages.map((msg) => {
    const m = msg as Record<string, unknown>;
    if (m.role !== 'tool' || !Array.isArray(m.content)) return msg;

    const newContent = (m.content as Record<string, unknown>[]).map((part) => {
      if (part.type !== 'tool-result' || !isPlainObject(part.result)) {
        return part;
      }
      const result = part.result as Record<string, unknown>;
      if (!('uiAction' in result)) return part;

      const { uiAction: _stripped, ...rest } = result;
      return { ...part, result: rest };
    });

    return { ...m, content: newContent } as T;
  });
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

// ---------------------------------------------------------------------------
// wrapToolsForVercelAi
// ---------------------------------------------------------------------------

interface SdkAiTool {
  description: string;
  parameters: unknown;
  needsApproval?: unknown;
  execute: (...args: unknown[]) => unknown;
}

/**
 * Convert SDK AI tools (output of `toolsToAiTools`) into Vercel AI SDK
 * `tool()` instances.
 *
 * @example
 * ```ts
 * import { wrapToolsForVercelAi } from './index.js';
 *
 * const vercelTools = wrapToolsForVercelAi(ctx.tools);
 * const result = streamText({ tools: vercelTools, ... });
 * ```
 */
export function wrapToolsForVercelAi(
  sdkTools: Record<string, unknown>,
): Record<string, unknown> {
  const wrapped: Record<string, unknown> = {};

  for (const [name, raw] of Object.entries(sdkTools)) {
    const sdkTool = raw as SdkAiTool;
    wrapped[name] = tool({
      description: sdkTool.description,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      inputSchema: zodSchema(sdkTool.parameters as any),
      needsApproval: sdkTool.needsApproval as Parameters<
        typeof tool
      >[0]['needsApproval'],
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      execute: sdkTool.execute as any,
    });
  }

  return wrapped;
}
