export { createLancer } from './client.js';
export { ServiceBlockedError } from './errors.js';
export type {
  AegisNamespace,
  AnalyzeOptions,
  AnalyzeResult,
  ApprovalCheckResult,
  ApprovalDecideResult,
  ApprovalResolveResult,
  ApprovalsNamespace,
  CheckResult,
  ClassifyResult,
  ConfigNamespace,
  ConfigResult,
  DegradationAction,
  DegradationContext,
  DegradationDefaults,
  Lancer,
  LancerConfig,
  LancerServiceName,
  LeakageResult,
  OnServiceUnavailable,
  PiiEntity,
  PrimusNamespace,
  PromptOverride,
  TelemetryEvent,
  TelemetryNamespace,
  Violation,
  WardenNamespace,
} from './types.js';
