import { useEffect, useCallback, useRef } from 'react';
import type { ActionIdRegistry } from '../types.js';

// ============================================================================
// Types
// ============================================================================

export interface UiAction {
  type: string;
  actionId?: string;
  [key: string]: unknown;
}

export type UiActionHandler = (action: UiAction) => void | Promise<void>;

export interface AiClientActionEventDetail {
  actionId: string;
  payload?: Record<string, unknown>;
}

// ============================================================================
// UiActionBus (class-based, framework-agnostic)
// ============================================================================

function addHandler(
  map: Map<string, Set<UiActionHandler>>,
  key: string,
  handler: UiActionHandler,
): () => void {
  const handlers = map.get(key) ?? new Set<UiActionHandler>();
  handlers.add(handler);
  map.set(key, handlers);

  return () => {
    const current = map.get(key);
    if (!current) return;
    current.delete(handler);
    if (current.size === 0) map.delete(key);
  };
}

export class UiActionBus {
  private handlersByType = new Map<string, Set<UiActionHandler>>();
  private handlersById = new Map<string, Set<UiActionHandler>>();

  subscribeByType(type: string, handler: UiActionHandler): () => void {
    return addHandler(this.handlersByType, type, handler);
  }

  subscribeById(actionId: string, handler: UiActionHandler): () => void {
    return addHandler(this.handlersById, actionId, handler);
  }

  async dispatch(action: UiAction): Promise<void> {
    const typeHandlers = this.handlersByType.get(action.type);
    const idHandlers = action.actionId
      ? this.handlersById.get(action.actionId)
      : undefined;

    const allHandlers = new Set<UiActionHandler>([
      ...(typeHandlers ? Array.from(typeHandlers) : []),
      ...(idHandlers ? Array.from(idHandlers) : []),
    ]);

    for (const handler of allHandlers) {
      await handler(action);
    }
  }
}

// ============================================================================
// UiActionBus Hooks
// ============================================================================

export function useAiClientActionByType(
  bus: UiActionBus,
  actionType: string,
  handler: UiActionHandler,
): void {
  useEffect(
    () => bus.subscribeByType(actionType, handler),
    [bus, actionType, handler],
  );
}

export function useAiClientActionById(
  bus: UiActionBus,
  actionId: string,
  handler: UiActionHandler,
): void {
  useEffect(
    () => bus.subscribeById(actionId, handler),
    [bus, actionId, handler],
  );
}

// ============================================================================
// Window Event-based Action Dispatch (to-do-manager pattern)
// ============================================================================

const AI_CLIENT_ACTION_EVENT = 'ai-client-action';

/** Global registry of currently registered handler actionIds */
const registeredHandlers = new Set<string>();

/** Optional reference to an ActionIdRegistry for validation */
let actionIdRegistryRef: ActionIdRegistry | undefined;

/**
 * Set the action ID registry for validation (call once at app startup).
 * The registry is typically auto-generated by the codegen package.
 */
export function setActionIdRegistry(registry: ActionIdRegistry): void {
  actionIdRegistryRef = registry;
}

/**
 * Dispatch an AI client action via window events.
 * Used by the chat panel / AI layer to trigger UI updates.
 */
export function dispatchAiClientAction(
  detail: AiClientActionEventDetail,
): void {
  if (typeof window === 'undefined') return;
  window.dispatchEvent(
    new CustomEvent(AI_CLIENT_ACTION_EVENT, { detail }),
  );
}

/**
 * Dispatch one or more AI client actions via window events.
 * Convenience wrapper for compound actions — accepts a single action or an array.
 */
export function dispatchAiClientActions(
  details: AiClientActionEventDetail | AiClientActionEventDetail[],
): void {
  const actions = Array.isArray(details) ? details : [details];
  for (const detail of actions) {
    dispatchAiClientAction(detail);
  }
}

/**
 * Hook to register a handler for a specific AI client action ID.
 * The handler is tracked in a global registry for dev-mode validation.
 *
 * @example
 * ```tsx
 * useAiClientAction('task-details.open', (payload) => {
 *   openTaskDetails(payload?.taskId as string);
 * });
 * ```
 */
export function useAiClientAction(
  actionId: string,
  handler: (payload?: Record<string, unknown>) => void,
): void {
  const handlerRef = useRef(handler);
  handlerRef.current = handler;

  const stableHandler = useCallback(
    (payload?: Record<string, unknown>) => handlerRef.current(payload),
    [],
  );

  useEffect(() => {
    registeredHandlers.add(actionId);

    const handleEvent = (event: Event) => {
      const detail = (event as CustomEvent<AiClientActionEventDetail>)
        .detail;
      if (!detail || detail.actionId !== actionId) return;
      stableHandler(detail.payload);
    };

    window.addEventListener(AI_CLIENT_ACTION_EVENT, handleEvent);
    return () => {
      window.removeEventListener(AI_CLIENT_ACTION_EVENT, handleEvent);
      registeredHandlers.delete(actionId);
    };
  }, [actionId, stableHandler]);
}

// ============================================================================
// Handler Registry Inspection (for dev-mode validation)
// ============================================================================

/**
 * Returns all currently registered handler actionIds.
 */
export function getRegisteredHandlers(): string[] {
  return Array.from(registeredHandlers);
}

/**
 * Returns actionIds defined in the registry but missing a registered handler.
 * Useful for dev-mode validation to ensure all AI actions have handlers.
 */
export function getMissingHandlers(): string[] {
  if (!actionIdRegistryRef) return [];
  const required = Object.keys(actionIdRegistryRef);
  return required.filter((id) => !registeredHandlers.has(id));
}

/**
 * Returns info about a specific actionId from the registry.
 */
export function getActionIdInfo(actionId: string) {
  return actionIdRegistryRef?.[actionId];
}

// ============================================================================
// Dev-Mode Missing Handler Warning
// ============================================================================

/**
 * Hook that warns about missing AI action handlers in development mode.
 * Checks after a 2-second delay to allow all components to mount and register.
 *
 * @example
 * ```tsx
 * // In your AppShell or root layout component:
 * useAiMissingHandlerWarning();
 * ```
 */
export function useAiMissingHandlerWarning(
  options: { delay?: number } = {},
): void {
  const { delay = 2000 } = options;

  useEffect(() => {
    if (process.env.NODE_ENV !== 'development') return;
    if (!actionIdRegistryRef) return;

    const timer = setTimeout(() => {
      const missing = getMissingHandlers();
      if (missing.length === 0) return;

      console.warn(
        `[glirastes] ${missing.length} AI action handler(s) missing:`,
        missing,
      );
      console.warn(
        '[glirastes] Register handlers with useAiClientAction() or mark as @ai-ignore',
      );
    }, delay);

    return () => clearTimeout(timer);
  }, [delay]);
}
